using Icarus_Item_Calculator.Models;
using Microsoft.EntityFrameworkCore;
using System.Reflection.Emit;

public class ItemContext : DbContext
{
    public ItemContext(DbContextOptions<ItemContext> options) : base(options) { }

    public DbSet<Item> Items { get; set; }
    public DbSet<RecipeItem> RecipeItems { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Item>()
            .Property(i => i.ItemId)
            .ValueGeneratedOnAdd();

        modelBuilder.Entity<RecipeItem>()
            .HasOne(ri => ri.Item)
            .WithMany()
            .HasForeignKey(ri => ri.ItemId);

        modelBuilder.Entity<RecipeItem>()
            .HasOne(ri => ri.ParentItem)
            .WithMany(i => i.Recipe)
            .HasForeignKey(ri => ri.ParentItemId);

        // Seed data if necessary
        modelBuilder.Entity<Item>().HasData(
            new Item { ItemId = 1, Name = "Aluminium Ingot", IsBaseItem = false },
            new Item { ItemId = 2, Name = "Aluminum Ore", IsBaseItem = true },
            new Item { ItemId = 3, Name = "Basic Fertilizer", IsBaseItem = false },
            new Item { ItemId = 4, Name = "Bone", IsBaseItem = true },
            new Item { ItemId = 5, Name = "Carbon Fiber", IsBaseItem = false },
            new Item { ItemId = 6, Name = "Carbon Paste", IsBaseItem = false },
            new Item { ItemId = 7, Name = "Charcoal", IsBaseItem = true },
            new Item { ItemId = 8, Name = "Coal Ore", IsBaseItem = true },
            new Item { ItemId = 9, Name = "Cocoa Seed", IsBaseItem = true },
            new Item { ItemId = 10, Name = "Coffee Bean", IsBaseItem = true },
            new Item { ItemId = 11, Name = "Composite Paste", IsBaseItem = false },
            new Item { ItemId = 12, Name = "Composites", IsBaseItem = false },
            new Item { ItemId = 13, Name = "Concrete Mix", IsBaseItem = false },
            new Item { ItemId = 14, Name = "Copper Ingot", IsBaseItem = false },
            new Item { ItemId = 15, Name = "Copper Nail", IsBaseItem = false },
            new Item { ItemId = 16, Name = "Copper Ore", IsBaseItem = true },
            new Item { ItemId = 17, Name = "Copper Wire", IsBaseItem = false },
            new Item { ItemId = 18, Name = "Corn", IsBaseItem = true },
            new Item { ItemId = 19, Name = "Crushed Bone", IsBaseItem = false },
            new Item { ItemId = 20, Name = "Dirt", IsBaseItem = true },
            new Item { ItemId = 21, Name = "Electronics", IsBaseItem = false },
            new Item { ItemId = 22, Name = "Epoxy", IsBaseItem = false },
            new Item { ItemId = 23, Name = "Exotics", IsBaseItem = true },
            new Item { ItemId = 24, Name = "Fiber", IsBaseItem = true },
            new Item { ItemId = 25, Name = "Fish Chunks", IsBaseItem = true },
            new Item { ItemId = 26, Name = "Flour", IsBaseItem = false },
            new Item { ItemId = 27, Name = "Fur", IsBaseItem = true },
            new Item { ItemId = 28, Name = "Glass", IsBaseItem = false },
            new Item { ItemId = 29, Name = "Gold Ore", IsBaseItem = true },
            new Item { ItemId = 30, Name = "Gold Wire", IsBaseItem = false },
            new Item { ItemId = 31, Name = "Gorse Flower", IsBaseItem = true },
            new Item { ItemId = 32, Name = "Growth Fertilizer", IsBaseItem = false },
            new Item { ItemId = 33, Name = "Gunpowder", IsBaseItem = false },
            new Item { ItemId = 34, Name = "High-Quality Fertilizer", IsBaseItem = false },
            new Item { ItemId = 35, Name = "Ice", IsBaseItem = true },
            new Item { ItemId = 36, Name = "Iron Ingot", IsBaseItem = false },
            new Item { ItemId = 37, Name = "Iron Nail", IsBaseItem = false },
            new Item { ItemId = 38, Name = "Iron Ore", IsBaseItem = true },
            new Item { ItemId = 39, Name = "Leather", IsBaseItem = true },
            new Item { ItemId = 40, Name = "Lily", IsBaseItem = true },
            new Item { ItemId = 41, Name = "Mammoth Tusk", IsBaseItem = true },
            new Item { ItemId = 42, Name = "Organic Resin", IsBaseItem = false },
            new Item { ItemId = 43, Name = "Oxite", IsBaseItem = true },
            new Item { ItemId = 44, Name = "Platinum Ingot", IsBaseItem = false },
            new Item { ItemId = 45, Name = "Platinum Ore", IsBaseItem = true },
            new Item { ItemId = 46, Name = "Poison Paste", IsBaseItem = false },
            new Item { ItemId = 47, Name = "Poison Sack", IsBaseItem = true },
            new Item { ItemId = 48, Name = "Polar Bear Pelt", IsBaseItem = true },
            new Item { ItemId = 49, Name = "Raw Meat", IsBaseItem = true },
            new Item { ItemId = 50, Name = "Raw Prime Meat", IsBaseItem = true },
            new Item { ItemId = 51, Name = "Reed Flower", IsBaseItem = true },
            new Item { ItemId = 52, Name = "Refined Gold", IsBaseItem = false },
            new Item { ItemId = 53, Name = "Refined Wood", IsBaseItem = false },
            new Item { ItemId = 54, Name = "Rope", IsBaseItem = false },
            new Item { ItemId = 55, Name = "Salt", IsBaseItem = true },
            new Item { ItemId = 56, Name = "Sandworm Scale", IsBaseItem = true },
            new Item { ItemId = 57, Name = "Scorpion Pincer", IsBaseItem = true },
            new Item { ItemId = 58, Name = "Scorpion Tail", IsBaseItem = true },
            new Item { ItemId = 59, Name = "Silica Ore", IsBaseItem = true },
            new Item { ItemId = 60, Name = "Spoiled Meat", IsBaseItem = true },
            new Item { ItemId = 61, Name = "Spoiled Plants", IsBaseItem = true },
            new Item { ItemId = 62, Name = "Sponge", IsBaseItem = true },
            new Item { ItemId = 63, Name = "Squash", IsBaseItem = true },
            new Item { ItemId = 64, Name = "Steel Bloom", IsBaseItem = false },
            new Item { ItemId = 65, Name = "Steel Ingot", IsBaseItem = false },
            new Item { ItemId = 66, Name = "Steel Rebar", IsBaseItem = false },
            new Item { ItemId = 67, Name = "Steel Screw", IsBaseItem = false },
            new Item { ItemId = 68, Name = "Stick", IsBaseItem = false },
            new Item { ItemId = 69, Name = "Stone", IsBaseItem = true },
            new Item { ItemId = 70, Name = "Sulfur", IsBaseItem = true },
            new Item { ItemId = 71, Name = "Tea", IsBaseItem = true },
            new Item { ItemId = 72, Name = "Titanium Ingot", IsBaseItem = false },
            new Item { ItemId = 73, Name = "Titanium Ore", IsBaseItem = true },
            new Item { ItemId = 74, Name = "Tree Sap", IsBaseItem = false },
            new Item { ItemId = 75, Name = "Wheat", IsBaseItem = true },
            new Item { ItemId = 76, Name = "Wild Berry", IsBaseItem = true },
            new Item { ItemId = 77, Name = "Wood", IsBaseItem = true },
            new Item { ItemId = 78, Name = "Worm Scale", IsBaseItem = true },
            new Item { ItemId = 79, Name = "Yeast", IsBaseItem = true },
            new Item { ItemId = 80, Name = "Crafting Bench", IsBaseItem = false },
            new Item { ItemId = 81, Name = "Anvil Bench", IsBaseItem = false },
            new Item { ItemId = 82, Name = "Wood Composter", IsBaseItem = false },
            new Item { ItemId = 83, Name = "Skinning Bench", IsBaseItem = false },
            new Item { ItemId = 84, Name = "Trophy Bench", IsBaseItem = false },
            new Item { ItemId = 85, Name = "Basic Fishing Bench", IsBaseItem = false },
            new Item { ItemId = 86, Name = "Mortar and Pestle", IsBaseItem = false },
            new Item { ItemId = 87, Name = "Herbalism Bench", IsBaseItem = false },
            new Item { ItemId = 88, Name = "Textiles Bench", IsBaseItem = false },
            new Item { ItemId = 89, Name = "Carpentry Bench", IsBaseItem = false },
            new Item { ItemId = 90, Name = "Masonry Bench", IsBaseItem = false },
            new Item { ItemId = 91, Name = "Machining Bench", IsBaseItem = false },
            new Item { ItemId = 92, Name = "Cement Mixer", IsBaseItem = false },
            new Item { ItemId = 93, Name = "Glassworking Bench", IsBaseItem = false },
            new Item { ItemId = 94, Name = "Advanced Textiles Bench", IsBaseItem = false },
            new Item { ItemId = 95, Name = "Alteration Bench", IsBaseItem = false },
            new Item { ItemId = 96, Name = "Fabricator", IsBaseItem = false },
            new Item { ItemId = 97, Name = "Material Processor", IsBaseItem = false },
            new Item { ItemId = 98, Name = "Chemistry Bench", IsBaseItem = false },
            new Item { ItemId = 99, Name = "Electric Textiles Bench", IsBaseItem = false },
            new Item { ItemId = 100, Name = "Advanced Alteration Bench", IsBaseItem = false },
            new Item { ItemId = 101, Name = "Electric Carpentry Bench", IsBaseItem = false },
            new Item { ItemId = 102, Name = "Electric Masonry Bench", IsBaseItem = false },
            new Item { ItemId = 103, Name = "Stone Furnace", IsBaseItem = false },
            new Item { ItemId = 104, Name = "Concrete Furnace", IsBaseItem = false },
            new Item { ItemId = 105, Name = "Electric Furnace", IsBaseItem = false },
            new Item { ItemId = 106, Name = "MXC Furnace", IsBaseItem = false },
            new Item { ItemId = 107, Name = "Campfire", IsBaseItem = false },
            new Item { ItemId = 108, Name = "Drying Rack", IsBaseItem = false },
            new Item { ItemId = 109, Name = "Firepit", IsBaseItem = false },
            new Item { ItemId = 110, Name = "Fireplace", IsBaseItem = false },
            new Item { ItemId = 111, Name = "Cooking Station", IsBaseItem = false },
            new Item { ItemId = 112, Name = "Potbelly Stove", IsBaseItem = false },
            new Item { ItemId = 113, Name = "Kitchen Bench", IsBaseItem = false },
            new Item { ItemId = 114, Name = "Biofuel Stove", IsBaseItem = false },
            new Item { ItemId = 115, Name = "Marble Kitchen Bench", IsBaseItem = false },
            new Item { ItemId = 116, Name = "Electric Stove", IsBaseItem = false },
            new Item { ItemId = 117, Name = "MXC Campfire", IsBaseItem = false },
            new Item { ItemId = 118, Name = "Salting Station", IsBaseItem = false },
            new Item { ItemId = 119, Name = "Ice Box", IsBaseItem = false },
            new Item { ItemId = 120, Name = "Refrigerator", IsBaseItem = false },
            new Item { ItemId = 121, Name = "Deep Freeze", IsBaseItem = false },
            new Item { ItemId = 122, Name = "Wood Pile", IsBaseItem = false },
            new Item { ItemId = 123, Name = "Stone Pile", IsBaseItem = false },
            new Item { ItemId = 124, Name = "Oxidizer", IsBaseItem = false },
            new Item { ItemId = 125, Name = "Oxite Dissolver", IsBaseItem = false },
            new Item { ItemId = 126, Name = "Biofuel Oxite Dissolver", IsBaseItem = false },
            new Item { ItemId = 127, Name = "Dehumidifier", IsBaseItem = false },
            new Item { ItemId = 128, Name = "Electric Dehumidifier", IsBaseItem = false },
            new Item { ItemId = 129, Name = "Floor Torch", IsBaseItem = false },
            new Item { ItemId = 130, Name = "Brazier", IsBaseItem = false },
            new Item { ItemId = 131, Name = "Wall Torch", IsBaseItem = false },
            new Item { ItemId = 132, Name = "Basic Wall Light", IsBaseItem = false },
            new Item { ItemId = 133, Name = "Basic Ceiling Light", IsBaseItem = false },
            new Item { ItemId = 134, Name = "Directional Worklamp", IsBaseItem = false },
            new Item { ItemId = 135, Name = "Omnidirectional Worklamp", IsBaseItem = false },
            new Item { ItemId = 136, Name = "Heavy Heater", IsBaseItem = false },
            new Item { ItemId = 137, Name = "Heavy Air Conditioner", IsBaseItem = false },
            new Item { ItemId = 138, Name = "Rain Reservoir", IsBaseItem = false },
            new Item { ItemId = 139, Name = "Electric Water Pump", IsBaseItem = false },
            new Item { ItemId = 140, Name = "Biofuel Composter", IsBaseItem = false },
            new Item { ItemId = 141, Name = "Electric Composter", IsBaseItem = false },
            new Item { ItemId = 142, Name = "Biofuel Generator", IsBaseItem = false },
            new Item { ItemId = 143, Name = "Solar Panel", IsBaseItem = false },
            new Item { ItemId = 144, Name = "Water Wheel", IsBaseItem = false },
            new Item { ItemId = 145, Name = "Wind Turbine", IsBaseItem = false },
            new Item { ItemId = 146, Name = "Portable Biofuel Generator", IsBaseItem = false },
            new Item { ItemId = 147, Name = "Biofuel Radar", IsBaseItem = false },
            new Item { ItemId = 148, Name = "Biofuel Extractor", IsBaseItem = false },
            new Item { ItemId = 149, Name = "Electric Radar", IsBaseItem = false },
            new Item { ItemId = 150, Name = "Electric Extractor", IsBaseItem = false },
            new Item { ItemId = 151, Name = "Medium Wood Hedgehog", IsBaseItem = false },
            new Item { ItemId = 152, Name = "Wood Gate Fortification", IsBaseItem = false },
            new Item { ItemId = 153, Name = "Wood Wall Fortification", IsBaseItem = false },
            new Item { ItemId = 154, Name = "Wood Spikes Fortification", IsBaseItem = false },
            new Item { ItemId = 155, Name = "Lightning Rod", IsBaseItem = false },
            new Item { ItemId = 156, Name = "Water Sprinkler", IsBaseItem = false },
            new Item { ItemId = 157, Name = "Scorpion Pincer Trap", IsBaseItem = false },
            new Item { ItemId = 158, Name = "Scorpion Hedgehog", IsBaseItem = false },
            new Item { ItemId = 159, Name = "Wood Crop Plot", IsBaseItem = false },
            new Item { ItemId = 160, Name = "Iron Crop Plot", IsBaseItem = false },
            new Item { ItemId = 161, Name = "Hydroponic Crop Plot", IsBaseItem = false },
            new Item { ItemId = 162, Name = "Animal Bait", IsBaseItem = false },
            new Item { ItemId = 163, Name = "Poisoned Animal Bait", IsBaseItem = false },
            new Item { ItemId = 164, Name = "Titanium Plate", IsBaseItem = false },
            new Item { ItemId = 165, Name = "Flow Meter", IsBaseItem = false },
            new Item { ItemId = 166, Name = "Biofuel Deep-Mining Drill", IsBaseItem = false },
            new Item { ItemId = 167, Name = "Electric Deep-Mining Drill", IsBaseItem = false },
            new Item { ItemId = 168, Name = "Animal Fat", IsBaseItem = false },
            new Item { ItemId = 169, Name = "Electrolytic Oxygen Synthesizer", IsBaseItem = false }
        );

        modelBuilder.Entity<RecipeItem>().HasData(
            new RecipeItem { RecipeItemId = 1, ParentItemId = 1, ItemId = 2, Quantity = 1 },
            new RecipeItem { RecipeItemId = 2, ParentItemId = 3, ItemId = 61, Quantity = 10 },
            new RecipeItem { RecipeItemId = 3, ParentItemId = 3, ItemId = 20, Quantity = 10 },
            new RecipeItem { RecipeItemId = 4, ParentItemId = 5, ItemId = 6, Quantity = 1 },
            new RecipeItem { RecipeItemId = 5, ParentItemId = 6, ItemId = 59, Quantity = 1 },
            new RecipeItem { RecipeItemId = 6, ParentItemId = 6, ItemId = 1, Quantity = 1 },
            new RecipeItem { RecipeItemId = 7, ParentItemId = 6, ItemId = 22, Quantity = 2 },
            new RecipeItem { RecipeItemId = 8, ParentItemId = 6, ItemId = 42, Quantity = 4 },
            new RecipeItem { RecipeItemId = 9, ParentItemId = 11, ItemId = 59, Quantity = 1 },
            new RecipeItem { RecipeItemId = 10, ParentItemId = 11, ItemId = 38, Quantity = 2 },
            new RecipeItem { RecipeItemId = 11, ParentItemId = 11, ItemId = 29, Quantity = 1 },
            new RecipeItem { RecipeItemId = 12, ParentItemId = 11, ItemId = 42, Quantity = 1 },
            new RecipeItem { RecipeItemId = 13, ParentItemId = 12, ItemId = 11, Quantity = 1 },
            new RecipeItem { RecipeItemId = 14, ParentItemId = 13, ItemId = 69, Quantity = 8 },
            new RecipeItem { RecipeItemId = 15, ParentItemId = 13, ItemId = 59, Quantity = 4 },
            new RecipeItem { RecipeItemId = 16, ParentItemId = 13, ItemId = 74, Quantity = 1 },
            new RecipeItem { RecipeItemId = 17, ParentItemId = 14, ItemId = 16, Quantity = 2 },
            new RecipeItem { RecipeItemId = 18, ParentItemId = 15, ItemId = 14, Quantity = 1 },
            new RecipeItem { RecipeItemId = 19, ParentItemId = 17, ItemId = 14, Quantity = 0.2 },
            new RecipeItem { RecipeItemId = 20, ParentItemId = 19, ItemId = 4, Quantity = 2 },
            new RecipeItem { RecipeItemId = 21, ParentItemId = 21, ItemId = 22, Quantity = 2 },
            new RecipeItem { RecipeItemId = 22, ParentItemId = 21, ItemId = 42, Quantity = 2 },
            new RecipeItem { RecipeItemId = 23, ParentItemId = 21, ItemId = 17, Quantity = 15 },
            new RecipeItem { RecipeItemId = 24, ParentItemId = 21, ItemId = 30, Quantity = 5 },
            new RecipeItem { RecipeItemId = 25, ParentItemId = 22, ItemId = 70, Quantity = 2 },
            new RecipeItem { RecipeItemId = 26, ParentItemId = 22, ItemId = 74, Quantity = 4 },
            new RecipeItem { RecipeItemId = 27, ParentItemId = 26, ItemId = 75, Quantity = 10 },
            new RecipeItem { RecipeItemId = 28, ParentItemId = 28, ItemId = 59, Quantity = 1 },
            new RecipeItem { RecipeItemId = 29, ParentItemId = 30, ItemId = 52, Quantity = 0.2 },
            new RecipeItem { RecipeItemId = 30, ParentItemId = 32, ItemId = 59, Quantity = 5 },
            new RecipeItem { RecipeItemId = 31, ParentItemId = 32, ItemId = 3, Quantity = 1 },
            new RecipeItem { RecipeItemId = 32, ParentItemId = 33, ItemId = 70, Quantity = 1 },
            new RecipeItem { RecipeItemId = 33, ParentItemId = 33, ItemId = 7, Quantity = 3 },
            new RecipeItem { RecipeItemId = 34, ParentItemId = 34, ItemId = 70, Quantity = 5 },
            new RecipeItem { RecipeItemId = 35, ParentItemId = 34, ItemId = 3, Quantity = 1 },
            new RecipeItem { RecipeItemId = 36, ParentItemId = 36, ItemId = 38, Quantity = 2 },
            new RecipeItem { RecipeItemId = 37, ParentItemId = 37, ItemId = 36, Quantity = 0.1 },
            new RecipeItem { RecipeItemId = 38, ParentItemId = 42, ItemId = 77, Quantity = 1 },
            new RecipeItem { RecipeItemId = 39, ParentItemId = 42, ItemId = 43, Quantity = 1 },
            new RecipeItem { RecipeItemId = 40, ParentItemId = 44, ItemId = 45, Quantity = 5 },
            new RecipeItem { RecipeItemId = 41, ParentItemId = 46, ItemId = 60, Quantity = 2 },
            new RecipeItem { RecipeItemId = 42, ParentItemId = 46, ItemId = 70, Quantity = 1 },
            new RecipeItem { RecipeItemId = 43, ParentItemId = 52, ItemId = 29, Quantity = 2 },
            new RecipeItem { RecipeItemId = 44, ParentItemId = 53, ItemId = 77, Quantity = 0.2 },
            new RecipeItem { RecipeItemId = 45, ParentItemId = 54, ItemId = 24, Quantity = 12 },
            new RecipeItem { RecipeItemId = 46, ParentItemId = 64, ItemId = 8, Quantity = 1 },
            new RecipeItem { RecipeItemId = 47, ParentItemId = 64, ItemId = 38, Quantity = 6 },
            new RecipeItem { RecipeItemId = 48, ParentItemId = 65, ItemId = 64, Quantity = 1 },
            new RecipeItem { RecipeItemId = 49, ParentItemId = 66, ItemId = 65, Quantity = 0.1 },
            new RecipeItem { RecipeItemId = 50, ParentItemId = 67, ItemId = 65, Quantity = 0.01 },
            new RecipeItem { RecipeItemId = 51, ParentItemId = 74, ItemId = 68, Quantity = 4 },
            new RecipeItem { RecipeItemId = 52, ParentItemId = 72, ItemId = 73, Quantity = 5 },
            new RecipeItem { RecipeItemId = 54, ParentItemId = 80, ItemId = 24, Quantity = 60 },
            new RecipeItem { RecipeItemId = 55, ParentItemId = 80, ItemId = 39, Quantity = 20 },
            new RecipeItem { RecipeItemId = 56, ParentItemId = 80, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 57, ParentItemId = 80, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 58, ParentItemId = 81, ItemId = 36, Quantity = 40 },
            new RecipeItem { RecipeItemId = 59, ParentItemId = 81, ItemId = 69, Quantity = 10 },
            new RecipeItem { RecipeItemId = 60, ParentItemId = 81, ItemId = 77, Quantity = 20 },
            new RecipeItem { RecipeItemId = 61, ParentItemId = 82, ItemId = 61, Quantity = 5 },
            new RecipeItem { RecipeItemId = 62, ParentItemId = 82, ItemId = 69, Quantity = 10 },
            new RecipeItem { RecipeItemId = 63, ParentItemId = 82, ItemId = 70, Quantity = 5 },
            new RecipeItem { RecipeItemId = 64, ParentItemId = 82, ItemId = 77, Quantity = 25 },
            new RecipeItem { RecipeItemId = 65, ParentItemId = 83, ItemId = 24, Quantity = 60 },
            new RecipeItem { RecipeItemId = 66, ParentItemId = 83, ItemId = 39, Quantity = 20 },
            new RecipeItem { RecipeItemId = 67, ParentItemId = 83, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 68, ParentItemId = 83, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 69, ParentItemId = 84, ItemId = 15, Quantity = 50 },
            new RecipeItem { RecipeItemId = 70, ParentItemId = 84, ItemId = 36, Quantity = 2 },
            new RecipeItem { RecipeItemId = 71, ParentItemId = 84, ItemId = 54, Quantity = 12 },
            new RecipeItem { RecipeItemId = 72, ParentItemId = 84, ItemId = 77, Quantity = 60 },
            new RecipeItem { RecipeItemId = 73, ParentItemId = 85, ItemId = 15, Quantity = 12 },
            new RecipeItem { RecipeItemId = 74, ParentItemId = 85, ItemId = 36, Quantity = 5 },
            new RecipeItem { RecipeItemId = 75, ParentItemId = 85, ItemId = 54, Quantity = 10 },
            new RecipeItem { RecipeItemId = 76, ParentItemId = 85, ItemId = 77, Quantity = 25 },
            new RecipeItem { RecipeItemId = 77, ParentItemId = 86, ItemId = 59, Quantity = 4 },
            new RecipeItem { RecipeItemId = 78, ParentItemId = 86, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 79, ParentItemId = 87, ItemId = 24, Quantity = 12 },
            new RecipeItem { RecipeItemId = 80, ParentItemId = 87, ItemId = 68, Quantity = 20 },
            new RecipeItem { RecipeItemId = 81, ParentItemId = 87, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 82, ParentItemId = 87, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 83, ParentItemId = 88, ItemId = 24, Quantity = 60 },
            new RecipeItem { RecipeItemId = 84, ParentItemId = 88, ItemId = 68, Quantity = 20 },
            new RecipeItem { RecipeItemId = 85, ParentItemId = 88, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 86, ParentItemId = 88, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 87, ParentItemId = 89, ItemId = 15, Quantity = 120 },
            new RecipeItem { RecipeItemId = 88, ParentItemId = 89, ItemId = 54, Quantity = 12 },
            new RecipeItem { RecipeItemId = 89, ParentItemId = 89, ItemId = 77, Quantity = 80 },
            new RecipeItem { RecipeItemId = 90, ParentItemId = 90, ItemId = 37, Quantity = 120 },
            new RecipeItem { RecipeItemId = 91, ParentItemId = 90, ItemId = 39, Quantity = 12 },
            new RecipeItem { RecipeItemId = 92, ParentItemId = 90, ItemId = 54, Quantity = 12 },
            new RecipeItem { RecipeItemId = 93, ParentItemId = 90, ItemId = 77, Quantity = 80 },
            new RecipeItem { RecipeItemId = 94, ParentItemId = 91, ItemId = 22, Quantity = 10 },
            new RecipeItem { RecipeItemId = 95, ParentItemId = 91, ItemId = 36, Quantity = 40 },
            new RecipeItem { RecipeItemId = 96, ParentItemId = 91, ItemId = 37, Quantity = 120 },
            new RecipeItem { RecipeItemId = 97, ParentItemId = 91, ItemId = 54, Quantity = 24 },
            new RecipeItem { RecipeItemId = 98, ParentItemId = 91, ItemId = 69, Quantity = 12 },
            new RecipeItem { RecipeItemId = 99, ParentItemId = 91, ItemId = 77, Quantity = 20 },
            new RecipeItem { RecipeItemId = 100, ParentItemId = 92, ItemId = 36, Quantity = 20 },
            new RecipeItem { RecipeItemId = 101, ParentItemId = 92, ItemId = 37, Quantity = 8 },
            new RecipeItem { RecipeItemId = 102, ParentItemId = 92, ItemId = 53, Quantity = 50 },
            new RecipeItem { RecipeItemId = 103, ParentItemId = 92, ItemId = 54, Quantity = 8 },
            new RecipeItem { RecipeItemId = 104, ParentItemId = 92, ItemId = 69, Quantity = 40 },
            new RecipeItem { RecipeItemId = 105, ParentItemId = 93, ItemId = 15, Quantity = 40 },
            new RecipeItem { RecipeItemId = 106, ParentItemId = 93, ItemId = 22, Quantity = 6 },
            new RecipeItem { RecipeItemId = 107, ParentItemId = 93, ItemId = 36, Quantity = 24 },
            new RecipeItem { RecipeItemId = 108, ParentItemId = 93, ItemId = 53, Quantity = 10 },
            new RecipeItem { RecipeItemId = 109, ParentItemId = 93, ItemId = 54, Quantity = 6 },
            new RecipeItem { RecipeItemId = 110, ParentItemId = 94, ItemId = 22, Quantity = 8 },
            new RecipeItem { RecipeItemId = 111, ParentItemId = 94, ItemId = 36, Quantity = 20 },
            new RecipeItem { RecipeItemId = 112, ParentItemId = 94, ItemId = 54, Quantity = 4 },
            new RecipeItem { RecipeItemId = 113, ParentItemId = 94, ItemId = 67, Quantity = 40 },
            new RecipeItem { RecipeItemId = 114, ParentItemId = 94, ItemId = 77, Quantity = 6 },
            new RecipeItem { RecipeItemId = 115, ParentItemId = 95, ItemId = 15, Quantity = 40 },
            new RecipeItem { RecipeItemId = 116, ParentItemId = 95, ItemId = 22, Quantity = 6 },
            new RecipeItem { RecipeItemId = 117, ParentItemId = 95, ItemId = 36, Quantity = 24 },
            new RecipeItem { RecipeItemId = 118, ParentItemId = 95, ItemId = 53, Quantity = 10 },
            new RecipeItem { RecipeItemId = 119, ParentItemId = 95, ItemId = 54, Quantity = 6 },
            new RecipeItem { RecipeItemId = 120, ParentItemId = 96, ItemId = 1, Quantity = 40 },
            new RecipeItem { RecipeItemId = 121, ParentItemId = 96, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 122, ParentItemId = 96, ItemId = 13, Quantity = 30 },
            new RecipeItem { RecipeItemId = 123, ParentItemId = 96, ItemId = 21, Quantity = 30 },
            new RecipeItem { RecipeItemId = 124, ParentItemId = 96, ItemId = 67, Quantity = 30 },
            new RecipeItem { RecipeItemId = 130, ParentItemId = 97, ItemId = 1, Quantity = 30 },
            new RecipeItem { RecipeItemId = 131, ParentItemId = 97, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 132, ParentItemId = 97, ItemId = 21, Quantity = 60 },
            new RecipeItem { RecipeItemId = 133, ParentItemId = 97, ItemId = 67, Quantity = 12 },
            new RecipeItem { RecipeItemId = 134, ParentItemId = 97, ItemId = 164, Quantity = 3 },
            new RecipeItem { RecipeItemId = 135, ParentItemId = 164, ItemId = 72, Quantity = 3 },
            new RecipeItem { RecipeItemId = 136, ParentItemId = 98, ItemId = 12, Quantity = 10 },
            new RecipeItem { RecipeItemId = 137, ParentItemId = 98, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 138, ParentItemId = 98, ItemId = 28, Quantity = 10 },
            new RecipeItem { RecipeItemId = 139, ParentItemId = 98, ItemId = 53, Quantity = 30 },
            new RecipeItem { RecipeItemId = 140, ParentItemId = 98, ItemId = 65, Quantity = 20 },
            new RecipeItem { RecipeItemId = 141, ParentItemId = 99, ItemId = 13, Quantity = 15 },
            new RecipeItem { RecipeItemId = 142, ParentItemId = 99, ItemId = 21, Quantity = 8 },
            new RecipeItem { RecipeItemId = 143, ParentItemId = 99, ItemId = 65, Quantity = 30 },
            new RecipeItem { RecipeItemId = 144, ParentItemId = 99, ItemId = 67, Quantity = 18 },
            new RecipeItem { RecipeItemId = 145, ParentItemId = 100, ItemId = 13, Quantity = 25 },
            new RecipeItem { RecipeItemId = 146, ParentItemId = 100, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 147, ParentItemId = 100, ItemId = 28, Quantity = 4 },
            new RecipeItem { RecipeItemId = 148, ParentItemId = 100, ItemId = 65, Quantity = 30 },
            new RecipeItem { RecipeItemId = 149, ParentItemId = 100, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 150, ParentItemId = 101, ItemId = 12, Quantity = 10 },
            new RecipeItem { RecipeItemId = 151, ParentItemId = 101, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 152, ParentItemId = 101, ItemId = 36, Quantity = 40 },
            new RecipeItem { RecipeItemId = 153, ParentItemId = 101, ItemId = 65, Quantity = 60 },
            new RecipeItem { RecipeItemId = 154, ParentItemId = 101, ItemId = 67, Quantity = 10 },
            new RecipeItem { RecipeItemId = 155, ParentItemId = 102, ItemId = 12, Quantity = 10 },
            new RecipeItem { RecipeItemId = 156, ParentItemId = 102, ItemId = 13, Quantity = 100 },
            new RecipeItem { RecipeItemId = 157, ParentItemId = 102, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 158, ParentItemId = 102, ItemId = 65, Quantity = 60 },
            new RecipeItem { RecipeItemId = 159, ParentItemId = 102, ItemId = 67, Quantity = 10 },
            new RecipeItem { RecipeItemId = 160, ParentItemId = 103, ItemId = 39, Quantity = 12 },
            new RecipeItem { RecipeItemId = 161, ParentItemId = 103, ItemId = 68, Quantity = 4 },
            new RecipeItem { RecipeItemId = 162, ParentItemId = 103, ItemId = 69, Quantity = 80 },
            new RecipeItem { RecipeItemId = 163, ParentItemId = 103, ItemId = 77, Quantity = 12 },
            new RecipeItem { RecipeItemId = 164, ParentItemId = 104, ItemId = 13, Quantity = 20 },
            new RecipeItem { RecipeItemId = 165, ParentItemId = 104, ItemId = 22, Quantity = 12 },
            new RecipeItem { RecipeItemId = 166, ParentItemId = 104, ItemId = 36, Quantity = 12 },
            new RecipeItem { RecipeItemId = 167, ParentItemId = 104, ItemId = 54, Quantity = 8 },
            new RecipeItem { RecipeItemId = 168, ParentItemId = 105, ItemId = 13, Quantity = 80 },
            new RecipeItem { RecipeItemId = 169, ParentItemId = 105, ItemId = 21, Quantity = 60 },
            new RecipeItem { RecipeItemId = 170, ParentItemId = 105, ItemId = 28, Quantity = 4 },
            new RecipeItem { RecipeItemId = 171, ParentItemId = 105, ItemId = 65, Quantity = 30 },
            new RecipeItem { RecipeItemId = 172, ParentItemId = 105, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 173, ParentItemId = 107, ItemId = 24, Quantity = 8 },
            new RecipeItem { RecipeItemId = 174, ParentItemId = 107, ItemId = 68, Quantity = 8 },
            new RecipeItem { RecipeItemId = 175, ParentItemId = 107, ItemId = 69, Quantity = 24 },
            new RecipeItem { RecipeItemId = 176, ParentItemId = 108, ItemId = 24, Quantity = 50 },
            new RecipeItem { RecipeItemId = 177, ParentItemId = 108, ItemId = 68, Quantity = 25 },
            new RecipeItem { RecipeItemId = 178, ParentItemId = 108, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 179, ParentItemId = 109, ItemId = 69, Quantity = 100 },
            new RecipeItem { RecipeItemId = 180, ParentItemId = 109, ItemId = 77, Quantity = 25 },
            new RecipeItem { RecipeItemId = 181, ParentItemId = 110, ItemId = 69, Quantity = 120 },
            new RecipeItem { RecipeItemId = 182, ParentItemId = 110, ItemId = 77, Quantity = 30 },
            new RecipeItem { RecipeItemId = 183, ParentItemId = 111, ItemId = 24, Quantity = 8 },
            new RecipeItem { RecipeItemId = 184, ParentItemId = 111, ItemId = 36, Quantity = 4 },
            new RecipeItem { RecipeItemId = 185, ParentItemId = 111, ItemId = 68, Quantity = 8 },
            new RecipeItem { RecipeItemId = 186, ParentItemId = 111, ItemId = 69, Quantity = 24 },
            new RecipeItem { RecipeItemId = 187, ParentItemId = 112, ItemId = 14, Quantity = 8 },
            new RecipeItem { RecipeItemId = 188, ParentItemId = 112, ItemId = 22, Quantity = 10 },
            new RecipeItem { RecipeItemId = 189, ParentItemId = 112, ItemId = 36, Quantity = 40 },
            new RecipeItem { RecipeItemId = 190, ParentItemId = 113, ItemId = 15, Quantity = 20 },
            new RecipeItem { RecipeItemId = 191, ParentItemId = 113, ItemId = 22, Quantity = 20 },
            new RecipeItem { RecipeItemId = 192, ParentItemId = 113, ItemId = 36, Quantity = 8 },
            new RecipeItem { RecipeItemId = 193, ParentItemId = 113, ItemId = 53, Quantity = 30 },
            new RecipeItem { RecipeItemId = 194, ParentItemId = 114, ItemId = 15, Quantity = 4 },
            new RecipeItem { RecipeItemId = 195, ParentItemId = 114, ItemId = 22, Quantity = 20 },
            new RecipeItem { RecipeItemId = 196, ParentItemId = 114, ItemId = 53, Quantity = 30 },
            new RecipeItem { RecipeItemId = 197, ParentItemId = 114, ItemId = 65, Quantity = 24 },
            new RecipeItem { RecipeItemId = 198, ParentItemId = 114, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 199, ParentItemId = 115, ItemId = 1, Quantity = 20 },
            new RecipeItem { RecipeItemId = 200, ParentItemId = 115, ItemId = 12, Quantity = 2 },
            new RecipeItem { RecipeItemId = 201, ParentItemId = 115, ItemId = 13, Quantity = 10 },
            new RecipeItem { RecipeItemId = 202, ParentItemId = 115, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 203, ParentItemId = 115, ItemId = 69, Quantity = 100 },
            new RecipeItem { RecipeItemId = 204, ParentItemId = 116, ItemId = 1, Quantity = 20 },
            new RecipeItem { RecipeItemId = 205, ParentItemId = 116, ItemId = 12, Quantity = 10 },
            new RecipeItem { RecipeItemId = 206, ParentItemId = 116, ItemId = 17, Quantity = 8 },
            new RecipeItem { RecipeItemId = 207, ParentItemId = 116, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 208, ParentItemId = 116, ItemId = 28, Quantity = 12 },
            new RecipeItem { RecipeItemId = 209, ParentItemId = 116, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 210, ParentItemId = 118, ItemId = 7, Quantity = 25 },
            new RecipeItem { RecipeItemId = 211, ParentItemId = 118, ItemId = 24, Quantity = 60 },
            new RecipeItem { RecipeItemId = 212, ParentItemId = 118, ItemId = 69, Quantity = 25 },
            new RecipeItem { RecipeItemId = 213, ParentItemId = 118, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 214, ParentItemId = 119, ItemId = 15, Quantity = 4 },
            new RecipeItem { RecipeItemId = 215, ParentItemId = 119, ItemId = 36, Quantity = 8 },
            new RecipeItem { RecipeItemId = 216, ParentItemId = 119, ItemId = 39, Quantity = 24 },
            new RecipeItem { RecipeItemId = 217, ParentItemId = 119, ItemId = 54, Quantity = 8 },
            new RecipeItem { RecipeItemId = 218, ParentItemId = 119, ItemId = 77, Quantity = 40 },
            new RecipeItem { RecipeItemId = 219, ParentItemId = 120, ItemId = 1, Quantity = 40 },
            new RecipeItem { RecipeItemId = 220, ParentItemId = 120, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 221, ParentItemId = 120, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 222, ParentItemId = 120, ItemId = 67, Quantity = 12 },
            new RecipeItem { RecipeItemId = 223, ParentItemId = 121, ItemId = 1, Quantity = 20 },
            new RecipeItem { RecipeItemId = 224, ParentItemId = 121, ItemId = 5, Quantity = 10 },
            new RecipeItem { RecipeItemId = 225, ParentItemId = 121, ItemId = 21, Quantity = 15 },
            new RecipeItem { RecipeItemId = 226, ParentItemId = 121, ItemId = 44, Quantity = 20 },
            new RecipeItem { RecipeItemId = 227, ParentItemId = 121, ItemId = 67, Quantity = 15 },
            new RecipeItem { RecipeItemId = 228, ParentItemId = 122, ItemId = 77, Quantity = 100 },
            new RecipeItem { RecipeItemId = 229, ParentItemId = 123, ItemId = 69, Quantity = 100 },
            new RecipeItem { RecipeItemId = 230, ParentItemId = 124, ItemId = 4, Quantity = 10 },
            new RecipeItem { RecipeItemId = 231, ParentItemId = 124, ItemId = 24, Quantity = 24 },
            new RecipeItem { RecipeItemId = 232, ParentItemId = 124, ItemId = 39, Quantity = 20 },
            new RecipeItem { RecipeItemId = 233, ParentItemId = 124, ItemId = 68, Quantity = 8 },
            new RecipeItem { RecipeItemId = 234, ParentItemId = 125, ItemId = 4, Quantity = 8 },
            new RecipeItem { RecipeItemId = 235, ParentItemId = 125, ItemId = 39, Quantity = 24 },
            new RecipeItem { RecipeItemId = 236, ParentItemId = 125, ItemId = 77, Quantity = 18 },
            new RecipeItem { RecipeItemId = 242, ParentItemId = 126, ItemId = 17, Quantity = 50 },
            new RecipeItem { RecipeItemId = 243, ParentItemId = 126, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 244, ParentItemId = 126, ItemId = 22, Quantity = 12 },
            new RecipeItem { RecipeItemId = 245, ParentItemId = 126, ItemId = 28, Quantity = 4 },
            new RecipeItem { RecipeItemId = 246, ParentItemId = 126, ItemId = 65, Quantity = 15 },
            new RecipeItem { RecipeItemId = 247, ParentItemId = 127, ItemId = 17, Quantity = 50 },
            new RecipeItem { RecipeItemId = 248, ParentItemId = 127, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 249, ParentItemId = 127, ItemId = 22, Quantity = 12 },
            new RecipeItem { RecipeItemId = 250, ParentItemId = 127, ItemId = 28, Quantity = 4 },
            new RecipeItem { RecipeItemId = 251, ParentItemId = 127, ItemId = 65, Quantity = 15 },
            new RecipeItem { RecipeItemId = 252, ParentItemId = 128, ItemId = 1, Quantity = 20 },
            new RecipeItem { RecipeItemId = 253, ParentItemId = 128, ItemId = 12, Quantity = 20 },
            new RecipeItem { RecipeItemId = 254, ParentItemId = 128, ItemId = 21, Quantity = 35 },
            new RecipeItem { RecipeItemId = 255, ParentItemId = 128, ItemId = 28, Quantity = 15 },
            new RecipeItem { RecipeItemId = 256, ParentItemId = 128, ItemId = 67, Quantity = 12 },
            new RecipeItem { RecipeItemId = 257, ParentItemId = 129, ItemId = 24, Quantity = 20 },
            new RecipeItem { RecipeItemId = 258, ParentItemId = 129, ItemId = 68, Quantity = 8 },
            new RecipeItem { RecipeItemId = 259, ParentItemId = 129, ItemId = 70, Quantity = 8 },
            new RecipeItem { RecipeItemId = 260, ParentItemId = 130, ItemId = 14, Quantity = 4 },
            new RecipeItem { RecipeItemId = 261, ParentItemId = 130, ItemId = 36, Quantity = 20 },
            new RecipeItem { RecipeItemId = 267, ParentItemId = 165, ItemId = 1, Quantity = 6 },
            new RecipeItem { RecipeItemId = 268, ParentItemId = 165, ItemId = 17, Quantity = 10 },
            new RecipeItem { RecipeItemId = 269, ParentItemId = 165, ItemId = 21, Quantity = 2 },
            new RecipeItem { RecipeItemId = 270, ParentItemId = 165, ItemId = 28, Quantity = 2 },
            new RecipeItem { RecipeItemId = 271, ParentItemId = 165, ItemId = 30, Quantity = 10 },
            new RecipeItem { RecipeItemId = 272, ParentItemId = 143, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 273, ParentItemId = 143, ItemId = 12, Quantity = 18 },
            new RecipeItem { RecipeItemId = 274, ParentItemId = 143, ItemId = 21, Quantity = 30 },
            new RecipeItem { RecipeItemId = 275, ParentItemId = 143, ItemId = 28, Quantity = 60 },
            new RecipeItem { RecipeItemId = 276, ParentItemId = 143, ItemId = 67, Quantity = 10 },
            new RecipeItem { RecipeItemId = 277, ParentItemId = 166, ItemId = 14, Quantity = 10 },
            new RecipeItem { RecipeItemId = 278, ParentItemId = 166, ItemId = 17, Quantity = 50 },
            new RecipeItem { RecipeItemId = 279, ParentItemId = 166, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 280, ParentItemId = 166, ItemId = 22, Quantity = 12 },
            new RecipeItem { RecipeItemId = 281, ParentItemId = 166, ItemId = 65, Quantity = 12 },
            new RecipeItem { RecipeItemId = 282, ParentItemId = 167, ItemId = 1, Quantity = 25 },
            new RecipeItem { RecipeItemId = 283, ParentItemId = 167, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 284, ParentItemId = 167, ItemId = 21, Quantity = 15 },
            new RecipeItem { RecipeItemId = 285, ParentItemId = 167, ItemId = 67, Quantity = 12 },
            new RecipeItem { RecipeItemId = 286, ParentItemId = 167, ItemId = 72, Quantity = 8 },
            new RecipeItem { RecipeItemId = 287, ParentItemId = 131, ItemId = 36, Quantity = 8 },
            new RecipeItem { RecipeItemId = 288, ParentItemId = 131, ItemId = 39, Quantity = 8 },
            new RecipeItem { RecipeItemId = 289, ParentItemId = 131, ItemId = 70, Quantity = 8 },
            new RecipeItem { RecipeItemId = 290, ParentItemId = 131, ItemId = 77, Quantity = 4 },
            new RecipeItem { RecipeItemId = 291, ParentItemId = 132, ItemId = 17, Quantity = 40 },
            new RecipeItem { RecipeItemId = 292, ParentItemId = 132, ItemId = 28, Quantity = 6 },
            new RecipeItem { RecipeItemId = 293, ParentItemId = 132, ItemId = 36, Quantity = 15 },
            new RecipeItem { RecipeItemId = 294, ParentItemId = 133, ItemId = 17, Quantity = 40 },
            new RecipeItem { RecipeItemId = 295, ParentItemId = 133, ItemId = 28, Quantity = 6 },
            new RecipeItem { RecipeItemId = 296, ParentItemId = 133, ItemId = 36, Quantity = 15 },
            new RecipeItem { RecipeItemId = 297, ParentItemId = 134, ItemId = 1, Quantity = 10 },
            new RecipeItem { RecipeItemId = 298, ParentItemId = 134, ItemId = 12, Quantity = 5 },
            new RecipeItem { RecipeItemId = 299, ParentItemId = 134, ItemId = 21, Quantity = 2 },
            new RecipeItem { RecipeItemId = 300, ParentItemId = 134, ItemId = 28, Quantity = 5 },
            new RecipeItem { RecipeItemId = 301, ParentItemId = 135, ItemId = 1, Quantity = 20 },
            new RecipeItem { RecipeItemId = 302, ParentItemId = 135, ItemId = 12, Quantity = 10 },
            new RecipeItem { RecipeItemId = 303, ParentItemId = 135, ItemId = 21, Quantity = 2 },
            new RecipeItem { RecipeItemId = 304, ParentItemId = 135, ItemId = 28, Quantity = 5 },
            new RecipeItem { RecipeItemId = 305, ParentItemId = 136, ItemId = 1, Quantity = 40 },
            new RecipeItem { RecipeItemId = 306, ParentItemId = 136, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 307, ParentItemId = 136, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 308, ParentItemId = 136, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 309, ParentItemId = 137, ItemId = 1, Quantity = 40 },
            new RecipeItem { RecipeItemId = 310, ParentItemId = 137, ItemId = 5, Quantity = 8 },
            new RecipeItem { RecipeItemId = 311, ParentItemId = 137, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 312, ParentItemId = 137, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 313, ParentItemId = 138, ItemId = 39, Quantity = 8 },
            new RecipeItem { RecipeItemId = 314, ParentItemId = 138, ItemId = 68, Quantity = 8 },
            new RecipeItem { RecipeItemId = 315, ParentItemId = 138, ItemId = 69, Quantity = 60 },
            new RecipeItem { RecipeItemId = 316, ParentItemId = 138, ItemId = 77, Quantity = 24 },
            new RecipeItem { RecipeItemId = 317, ParentItemId = 139, ItemId = 13, Quantity = 20 },
            new RecipeItem { RecipeItemId = 318, ParentItemId = 139, ItemId = 21, Quantity = 4 },
            new RecipeItem { RecipeItemId = 319, ParentItemId = 139, ItemId = 65, Quantity = 24 },
            new RecipeItem { RecipeItemId = 320, ParentItemId = 139, ItemId = 67, Quantity = 16 },
            new RecipeItem { RecipeItemId = 321, ParentItemId = 140, ItemId = 13, Quantity = 12 },
            new RecipeItem { RecipeItemId = 322, ParentItemId = 140, ItemId = 14, Quantity = 8 },
            new RecipeItem { RecipeItemId = 323, ParentItemId = 140, ItemId = 36, Quantity = 20 },
            new RecipeItem { RecipeItemId = 324, ParentItemId = 140, ItemId = 67, Quantity = 20 },
            new RecipeItem { RecipeItemId = 325, ParentItemId = 141, ItemId = 12, Quantity = 20 },
            new RecipeItem { RecipeItemId = 326, ParentItemId = 141, ItemId = 13, Quantity = 100 },
            new RecipeItem { RecipeItemId = 327, ParentItemId = 141, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 328, ParentItemId = 141, ItemId = 65, Quantity = 60 },
            new RecipeItem { RecipeItemId = 329, ParentItemId = 141, ItemId = 67, Quantity = 20 },
            new RecipeItem { RecipeItemId = 330, ParentItemId = 142, ItemId = 17, Quantity = 40 },
            new RecipeItem { RecipeItemId = 331, ParentItemId = 142, ItemId = 21, Quantity = 12 },
            new RecipeItem { RecipeItemId = 332, ParentItemId = 142, ItemId = 28, Quantity = 2 },
            new RecipeItem { RecipeItemId = 333, ParentItemId = 142, ItemId = 65, Quantity = 20 },
            new RecipeItem { RecipeItemId = 334, ParentItemId = 142, ItemId = 67, Quantity = 20 },
            new RecipeItem { RecipeItemId = 335, ParentItemId = 144, ItemId = 15, Quantity = 50 },
            new RecipeItem { RecipeItemId = 336, ParentItemId = 144, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 337, ParentItemId = 144, ItemId = 42, Quantity = 25 },
            new RecipeItem { RecipeItemId = 338, ParentItemId = 144, ItemId = 65, Quantity = 10 },
            new RecipeItem { RecipeItemId = 339, ParentItemId = 144, ItemId = 69, Quantity = 50 },
            new RecipeItem { RecipeItemId = 340, ParentItemId = 144, ItemId = 77, Quantity = 100 },
            new RecipeItem { RecipeItemId = 341, ParentItemId = 147, ItemId = 17, Quantity = 50 },
            new RecipeItem { RecipeItemId = 342, ParentItemId = 147, ItemId = 28, Quantity = 2 },
            new RecipeItem { RecipeItemId = 343, ParentItemId = 147, ItemId = 30, Quantity = 50 },
            new RecipeItem { RecipeItemId = 344, ParentItemId = 147, ItemId = 36, Quantity = 12 },
            new RecipeItem { RecipeItemId = 345, ParentItemId = 147, ItemId = 37, Quantity = 8 },
            new RecipeItem { RecipeItemId = 346, ParentItemId = 148, ItemId = 15, Quantity = 10 },
            new RecipeItem { RecipeItemId = 347, ParentItemId = 148, ItemId = 30, Quantity = 25 },
            new RecipeItem { RecipeItemId = 348, ParentItemId = 148, ItemId = 36, Quantity = 15 },
            new RecipeItem { RecipeItemId = 349, ParentItemId = 149, ItemId = 12, Quantity = 12 },
            new RecipeItem { RecipeItemId = 350, ParentItemId = 149, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 351, ParentItemId = 149, ItemId = 28, Quantity = 2 },
            new RecipeItem { RecipeItemId = 352, ParentItemId = 149, ItemId = 65, Quantity = 12 },
            new RecipeItem { RecipeItemId = 353, ParentItemId = 149, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 354, ParentItemId = 150, ItemId = 21, Quantity = 5 },
            new RecipeItem { RecipeItemId = 355, ParentItemId = 150, ItemId = 36, Quantity = 20 },
            new RecipeItem { RecipeItemId = 357, ParentItemId = 151, ItemId = 54, Quantity = 4 },
            new RecipeItem { RecipeItemId = 358, ParentItemId = 151, ItemId = 77, Quantity = 60 },
            new RecipeItem { RecipeItemId = 359, ParentItemId = 152, ItemId = 36, Quantity = 6 },
            new RecipeItem { RecipeItemId = 360, ParentItemId = 152, ItemId = 54, Quantity = 4 },
            new RecipeItem { RecipeItemId = 361, ParentItemId = 152, ItemId = 77, Quantity = 40 },
            new RecipeItem { RecipeItemId = 362, ParentItemId = 153, ItemId = 37, Quantity = 18 },
            new RecipeItem { RecipeItemId = 363, ParentItemId = 153, ItemId = 54, Quantity = 12 },
            new RecipeItem { RecipeItemId = 364, ParentItemId = 153, ItemId = 77, Quantity = 50 },
            new RecipeItem { RecipeItemId = 365, ParentItemId = 154, ItemId = 54, Quantity = 6 },
            new RecipeItem { RecipeItemId = 366, ParentItemId = 154, ItemId = 77, Quantity = 80 },
            new RecipeItem { RecipeItemId = 367, ParentItemId = 155, ItemId = 14, Quantity = 10 },
            new RecipeItem { RecipeItemId = 368, ParentItemId = 156, ItemId = 17, Quantity = 4 },
            new RecipeItem { RecipeItemId = 369, ParentItemId = 156, ItemId = 22, Quantity = 4 },
            new RecipeItem { RecipeItemId = 370, ParentItemId = 156, ItemId = 65, Quantity = 2 },
            new RecipeItem { RecipeItemId = 371, ParentItemId = 157, ItemId = 57, Quantity = 1 },
            new RecipeItem { RecipeItemId = 372, ParentItemId = 157, ItemId = 68, Quantity = 4 },
            new RecipeItem { RecipeItemId = 373, ParentItemId = 157, ItemId = 69, Quantity = 4 },
            new RecipeItem { RecipeItemId = 374, ParentItemId = 158, ItemId = 58, Quantity = 1 },
            new RecipeItem { RecipeItemId = 375, ParentItemId = 158, ItemId = 151, Quantity = 1 },
            new RecipeItem { RecipeItemId = 376, ParentItemId = 159, ItemId = 20, Quantity = 20 },
            new RecipeItem { RecipeItemId = 377, ParentItemId = 159, ItemId = 70, Quantity = 10 },
            new RecipeItem { RecipeItemId = 378, ParentItemId = 159, ItemId = 77, Quantity = 8 },
            new RecipeItem { RecipeItemId = 379, ParentItemId = 160, ItemId = 17, Quantity = 20 },
            new RecipeItem { RecipeItemId = 380, ParentItemId = 160, ItemId = 20, Quantity = 20 },
            new RecipeItem { RecipeItemId = 381, ParentItemId = 160, ItemId = 36, Quantity = 10 },
            new RecipeItem { RecipeItemId = 382, ParentItemId = 160, ItemId = 67, Quantity = 8 },
            new RecipeItem { RecipeItemId = 383, ParentItemId = 160, ItemId = 70, Quantity = 12 },
            new RecipeItem { RecipeItemId = 384, ParentItemId = 161, ItemId = 12, Quantity = 20 },
            new RecipeItem { RecipeItemId = 385, ParentItemId = 161, ItemId = 17, Quantity = 20 },
            new RecipeItem { RecipeItemId = 386, ParentItemId = 161, ItemId = 20, Quantity = 20 },
            new RecipeItem { RecipeItemId = 387, ParentItemId = 161, ItemId = 21, Quantity = 10 },
            new RecipeItem { RecipeItemId = 388, ParentItemId = 161, ItemId = 65, Quantity = 10 },
            new RecipeItem { RecipeItemId = 389, ParentItemId = 161, ItemId = 67, Quantity = 25 },
            new RecipeItem { RecipeItemId = 390, ParentItemId = 168, ItemId = 49, Quantity = 1 },
            new RecipeItem { RecipeItemId = 391, ParentItemId = 162, ItemId = 49, Quantity = 1 },
            new RecipeItem { RecipeItemId = 392, ParentItemId = 162, ItemId = 168, Quantity = 2 },
            new RecipeItem { RecipeItemId = 393, ParentItemId = 163, ItemId = 46, Quantity = 2 },
            new RecipeItem { RecipeItemId = 394, ParentItemId = 163, ItemId = 162, Quantity = 1 },
            new RecipeItem { RecipeItemId = 395, ParentItemId = 146, ItemId = 17, Quantity = 20 },
            new RecipeItem { RecipeItemId = 396, ParentItemId = 146, ItemId = 21, Quantity = 6 },
            new RecipeItem { RecipeItemId = 397, ParentItemId = 146, ItemId = 28, Quantity = 2 },
            new RecipeItem { RecipeItemId = 398, ParentItemId = 146, ItemId = 65, Quantity = 10 },
            new RecipeItem { RecipeItemId = 399, ParentItemId = 146, ItemId = 67, Quantity = 10 },
            new RecipeItem { RecipeItemId = 400, ParentItemId = 169, ItemId = 17, Quantity = 70 },
            new RecipeItem { RecipeItemId = 401, ParentItemId = 169, ItemId = 21, Quantity = 20 },
            new RecipeItem { RecipeItemId = 402, ParentItemId = 169, ItemId = 28, Quantity = 10 },
            new RecipeItem { RecipeItemId = 403, ParentItemId = 169, ItemId = 164, Quantity = 2 }
        );
    }
}
